#!/usr/bin/env bash
# File: chkdate2
# Author: Ian Watt
# Email: iwatt@myseneca.ca
# Date: 2014-10-02
# Purpose: This script checks if a date if valid using the date command

# uncomment to debug script
#set -x

# store the scripts usage string
usage="Usage: chkdate2 year month day"

if [[ $# -ne 3 ]]; then
    echo $usage
    exit 1
fi

year=$1
month=$2
day=$3

date "+%d/%m/%Y" -d "$day/$month/$year"
is_valid=$?

if [[ $is_valid -eq 0 ]]; then
    echo "$day/$month/$year is a valid date"
    exit $is_valid
else
    echo "Invalid date!"
    echo $usage
    exit $is_valid
fi

